protocol-http1:
  url: https://github.com/socketry/protocol-http1.git
  command: bundle exec sus
protocol-http2:
  url: https://github.com/socketry/protocol-http2.git
  command: bundle exec sus
protocol-rack:
  url: https://github.com/socketry/protocol-rack.git
  command: bundle exec sus
async-http:
  url: https://github.com/socketry/async-http.git
  command: bundle exec sus
async-http-cache:
  url: https://github.com/socketry/async-http-cache.git
  command: bundle exec sus
protocol-websocket:
  url: https://github.com/socketry/protocol-websocket.git
  command: bundle exec sus
async-websocket:
  url: https://github.com/socketry/async-websocket.git
  command: bundle exec sus
falcon:
  url: https://github.com/socketry/falcon.git
  command: bundle exec sus
async-rest:
  url: https://github.com/socketry/async-rest.git
  command: bundle exec sus
async-grpc:
  url: https://github.com/socketry/async-grpc.git
  command: bundle exec sus
